  server:
    port: 9991
    
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/Hotel_UserService
      username: root
      password: nitinrai
      driver-class-name: com.mysql.cj.jdbc.Driver

    kafka:
      producer:
        bootstrap-servers:
          - localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


    
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          hibernate.jdbc.time_zone: UTC
    flyway:
      enabled: true
      locations:
        - classpath:db/migration
    
    sql:
      init:
        mode: ALWAYS
        data-locations:
          - classpath:init.sql
        continue-on-error: true


  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:9094/eureka